
#disable default springboot web server
spring:
  main:
    web-application-type: NONE

log-agent:
  # client id sent to service host to distinguish which client the logs come from	
  clientId: client1
  # url of the service host
  hostUrl: http://localhost:8081/log-aggregator/
  # delay (in seconds) between upload attempts to service host
  delayBetweenUploads: 5
