
#disable default springboot web server
spring:
  main:
    web-application-type: NONE

agent:
  # client id sent to service host to distinguish which client the logs come from	
  clientId: client-1
  # url of the service host
  hostUrl: foobar #https://localhost:8081/datastax-log/service
  # delay (in seconds) between upload attempts to service host
  delayBetweenUploads: 5
